engines:
  duplication:
    enabled: true
    config:
      languages:
      - python
  fixme:
    enabled: true
  radon:
    enabled: true
  pep8:
    enabled: true
  shellcheck:
    enabled: true
ratings:
  paths:
  - "**.py"
exclude_paths:
- tests/
- docs/
- config/
- web/
- README.rst
- COPYING
- INSTALL
- MANIFEST.in
- THANKS
- requirements.txt
- test.conf
