language: python
python:
  - "2.7"
  - "3.4"
  - "pypy"
  - "pypy3"
services:
  - redis-server
install: 
  - "./scripts/run_tests prepare"
script: 
  - "py.test tests/unit/ --cov pyzor --cov-report term-missing"
  - "py.test tests/functional/"
after_success:
  - coveralls
notifications:
  slack:
    secure: cjCoL6zEvbUGejQ39Xu4MNZHipxPux0+DG450js8S5L4+hSsch0FlHY1CP/Eeie0ko9QELhdWG1dB7Ndb7HQ5WVJsOhOA9mFYM5rBam4LZS1rv0Ggf0ASnfk0HDHiL0+f03ssneDNP4D8FhCdZl4FPgBPIUv2l+mTcWxHeoY4zM=
    
